# Generated by Django 3.0.5 on 2020-05-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_broker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('U', 'User'), ('S', 'Seller'), ('B', 'Broker')], default='none', max_length=1),
        ),
    ]
