# Generated by Django 3.0.5 on 2020-05-31 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200530_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('bedroom', models.PositiveIntegerField()),
                ('bathroom', models.PositiveIntegerField()),
                ('area', models.IntegerField()),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Test')),
            ],
        ),
    ]
