# Generated by Django 3.0.5 on 2020-04-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('username', models.CharField(default='enter unique username', max_length=25, unique=True)),
                ('email', models.EmailField(max_length=25)),
                ('password', models.CharField(default='enter unique password', max_length=25)),
                ('phonenumber', models.CharField(max_length=10)),
            ],
        ),
    ]
